# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: '/' # Location of package manifests
    rebase-strategy: 'disabled' # use dependabot-rebase-stale
    schedule:
      interval: 'daily'
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    ignore:
      - dependency-name: '@types/node'
    groups:
      patches:
        update-types:
          - 'patch'
      low-risk:
        patterns:
          - '@calcom/embed-react'
          - '@splinetool/react-spline'
          - 'lucide-react'
          - 'posthog-js'
          - 'react-icons'
